### PR TITLE
First pass at a unit test for channel rendering

### PR DESCRIPTION
**Pull request by DidierMalenfant**
This is not ready for prime time yet. Some modules fails to pass the test.

I'm posting it as a starting point and to illustrate the conversation in #3 about the precision problems I'm seeing.

To be clear, those problems may be perfectly normal and caused by the fact that mixing samples and mixing wav file channels (which is what I'm doing here) may not be comparable at all.

I'm still looking into this to make sure.

### CODE REVIEW

**Comment by DidierMalenfant** [comment]
> when I render "filter.mod" to a mixed file, then render it to individual channels, mix the channels together and invert it into the original file, there is complete silence. 

That's an interesting way of comparing, whereas I'm just comparing resulting samples after mixing takes place. Both should work or fail though... Let me try and repro your version.

> when grabbing the appropriate sample byte from the module - it converts the signed byte to unsigned, then takes 128 away to make it a true signed value

That confuses me. Maybe it's me by the way, I'm not well versed with audio stuff. What's a 'true' signed value?

**Comment by Prezzodaman** [comment]
I replaced the existing test code with the one in this pull request, and only 2 modules failed: "filter.mod" and "ode2ptk.mod".

"filter.mod" fails because there's some kind of bug related to rendering individual channels with the filter enabled. It appears to be a rounding issue in these lines of code:
```
channel_sum_left = (channel_sum_left + channel_sum_left_last) // 2
channel_sum_right = (channel_sum_right + channel_sum_right_last) // 2
```
I also tested this using the inversion method, and indeed, there are a handful of bytes in "filter.mod" that are off, but only on the sections with the filter enabled. This also rules out the sample bytes being miscalculated, because the non-filtered sections invert perfectly into each other. Unfortunately I have no idea how to fix this, but it seems like its own entire thing, so I'll make an issue dedicated to this bug.

"ode2ptk.mod" simply fails because of the offset problem (mentioned in issue #11). This means there's absolutely nothing wrong with your code, so no need to worry!

> What's a 'true' signed value?

I don't know the exact wording, but basically each sample is stored in the module as bytes between 0 and 255, but they're signed so I have to add 128, then perform a bitwise "and" with 255 to get an unsigned value. Then, by subtracting 128, I get a "true" signed value between -128 and 127. It basically means that positive and negative numbers are represented correctly before converting them back.

**Comment by Prezzodaman** [comment]
I've merged this pull request because I managed to get the "off by one" issue sorted - it wasn't a rounding issue as I suspected, it was actually due to the entire sum being filtered! I've changed it so each channel is filtered individually, and now all tests pass apart from "ode2ptk.mod" (for the same reason mentioned before). I've got some more stuff to fix, then I'll push the next working version featuring lots of fixes and new features (including legacy mode!)

**Comment by DidierMalenfant** [comment]
That's awesome!

> I don't know the exact wording, but basically each sample is stored in the module as bytes between 0 and 255, but they're signed so I have to add 128, then perform a bitwise "and" with 255

Why not just sign-extend the byte? (again I may be missing something here... :)

**Comment by Prezzodaman** [comment]
> Why not just sign-extend the byte? (again I may be missing something here... :)

You're not missing anything! I don't actually know the proper way of doing it :P

**Pull request merged**
